language: csharp
mono: none
dotnet: 1.0.0-preview2-003131
dist: trusty
sudo: false
env: DOTNETCORE=1

solution: JohannesBorg.sln

before_install:
  - time wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - nuget
  - nuget restore JohannesBorg.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - dotnet --version
  - dotnet /p:Configuration=Release JohannesBorg.sln
  - dotnet ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./JohannesBorg.Tests/bin/Release/JohannesBorg.Tests.dll