language: csharp
solution: JohannesBorg.sln
services:
  - mysql
  
install:
  - nuget restore JohannesBorg.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
  
before_script:
  - mysql -e 'SELECT NOW()'
  - mysql -e 'create database IF NOT EXISTS TEST_DB;'
  - mysql -e "use TEST_DB;" 
 
script:
  - xbuild /p:Configuration=Release JohannesBorg.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./JohannesBorg.Tests/bin/Release/JohannesBorg.Tests.dll --params=TestContext=Travis