language: csharp
solution: JohannesBorg.sln
mono: none
dotnet: 1.0.0-preview2-003131
dist: trusty
sudo: false

install:
  - nuget restore JohannesBorg.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - dotnet /p:Configuration=Release JohannesBorg.sln
  - dotnet ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./JohannesBorg.Tests/bin/Release/JohannesBorg.Tests.dll