language: csharp
solution: JohannesBorg.sln
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - nuget restore JohannesBorg.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release JohannesBorg.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./JohannesBorg.Tests/bin/Release/JohannesBorg.Tests.dll